
services:
  db:
    image: postgres:latest
    ports:
      - "5432:5432"
    env_file:
      - .env
    environment:
      POSTGRES_USER: "${PG_USER}"
      POSTGRES_PASSWORD: "${PG_PASSWORD}"
      POSTGRES_DB: "${PG_DB}"
    volumes:
      - pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${PG_USER} -d ${PG_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build:
      context: .
      dockerfile: Dockerfile
    command: "uv run uvicorn app.main:app --reload --host 0.0.0.0 --port 8000"
    ports:
     - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db  
    volumes:
      - ./certs:/app_root/certs:ro

volumes:
  pg_data:
  certs: