"""fixed tasks.description

Revision ID: 45cdfcd765c6
Revises: 0e60fdbaa6b5
Create Date: 2025-05-18 23:38:43.398035

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '45cdfcd765c6'
down_revision: Union[str, None] = '0e60fdbaa6b5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tasks', 'Description',
               existing_type=sa.TEXT(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tasks', 'Description',
               existing_type=sa.TEXT(),
               nullable=False)
    # ### end Alembic commands ###
